module.exports = {
  fr: {
    title: "NeoChess — Accueil",
    welcome: "Bienvenue",
    play: "Jouer",
    social: "Amies",
    langue: "langue",
    level: "niveau",
    readyQuestion: "Prêt pour votre prochaine partie ?",
    eloProgressed: "progressé",
    eloDeclined: "reculé",
    eloMonthSuffix: "ce mois.",
    lastGame: "Dernière partie",
    chess: "Échecs",
    boardAlt: "Échiquier — dernière partie",
    vs: "vs",
    noGamesPlayed: "Aucune partie jouée",
    win: "Victoire",
    loss: "Défaite",
    draw: "Nulle",
    eloRanking: "Classement ELO",
    lastMonths: "7 derniers mois",
    top: "Top",
    worldwide: "mondial",
    games: "Parties",
    wins: "Victoires",
    best: "Meilleur",
    globalRanking: "Classement Global",
    thisMonth: "Ce mois",
    you: "Vous",
    viewFullRanking: "Voir le classement complet",
  },
};
